"""updated class exam

Revision ID: 3fcc62d215dc
Revises: 1bbb64768385
Create Date: 2020-10-02 11:02:25.234948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcc62d215dc'
down_revision = '1bbb64768385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('module', sa.String(length=255), nullable=True))
    op.add_column('exams', sa.Column('topic', sa.String(length=255), nullable=True))
    op.drop_column('exams', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('exams', 'topic')
    op.drop_column('exams', 'module')
    # ### end Alembic commands ###
