"""deleted class topic and module

Revision ID: 90cd2177d723
Revises: 3fcc62d215dc
Create Date: 2020-10-02 12:10:08.268204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cd2177d723'
down_revision = '3fcc62d215dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Topics')
    op.drop_table('modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('modules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='modules_course_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='modules_school_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='modules_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='modules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Topics',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Topics_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='Topics_course_id_fkey'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='Topics_module_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='Topics_school_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Topics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Topics_pkey')
    )
    # ### end Alembic commands ###
